[package]
name = "dart_wasmer"
version = "0.1.0"
authors = ["Rody Davis <rody.davis.jr@gmail.com>"]
edition = "2018"

[lib]
name = "adder"
crate-type = ["cdylib"]

[dependencies]
wasmer-runtime = "0.13.1"
